name: test
on: [push, pull_request]
jobs:
  integration-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run unit & integration tests
        run: npm run test

      - name: Run end to end tests (in-memory database)
        run: npm run test:e2e:compose:inmemory

      - name: Run end to end tests (mysql database)
        run: npm run test:e2e:compose:mysql
